// User data model
export const fakeData = [
    {
      "userId": 1,
      "fullName": "John Doe",
      "customerId": 1001,
      "userLoginid": "johndoe",
      "password": "Pass@123",
      "emailAddress": "johndoe@example.com",
      "cellPhone": "+1234567890",
      "officeLandline": "+9876543210",
      "officeAddress": "123 Main St, City Center",
      "department": "IT",
      "city": "New York",
      "roleId": 2,
      "sms": true,
      "mail": true,
      "userStatus": "Active",
      "createdBy": "admin",
      "creationDate": "2024-03-12 10:30:00",
      "roleType": "Admin"
    },
    {
      "userId": 2,
      "fullName": "Jane Smith",
      "customerId": 1002,
      "userLoginid": "janesmith",
      "password": "Jane@123",
      "emailAddress": "janesmith@example.com",
      "cellPhone": "+1987654321",
      "officeLandline": "+9123456789",
      "officeAddress": "456 Elm St, Downtown",
      "department": "HR",
      "city": "Los Angeles",
      "roleId": 3,
      "sms": false,
      "mail": true,
      "userStatus": "Inactive",
      "createdBy": "admin",
      "creationDate": "2024-03-10 14:20:00 ",
      "roleType": "User"
    },
    {
      "userId": 3,
      "fullName": "Michael Brown",
      "customerId": 1003,
      "userLoginid": "michaelb",
      "password": "Michael@789",
      "emailAddress": "michaelb@example.com",
      "cellPhone": "+1765432987",
      "officeLandline": "+9012345678",
      "officeAddress": "789 Oak St, Uptown",
      "department": "Finance",
      "city": "Chicago",
      "roleId": 4,
      "sms": true,
      "mail": false,
      "userStatus": "Active",
      "createdBy": "superadmin",
      "creationDate": "2024-02-25 08:45:00",
      "roleType": "Manager"
    },
    {
      "userId": 4,
      "fullName": "Emily White",
      "customerId": 1004,
      "userLoginid": "emilyw",
      "password": "Emily@456",
      "emailAddress": "emilyw@example.com",
      "cellPhone": "+1678905432",
      "officeLandline": "+9234567890",
      "officeAddress": "321 Pine St, Midtown",
      "department": "Marketing",
      "city": "Houston",
      "roleId": 5,
      "sms": true,
      "mail": true,
      "userStatus": "Active",
      "createdBy": "admin",
      "creationDate": "2024-01-15 12:10:00Z",
      "roleType": "Supervisor"
    },
    {
      "userId": 5,
      "fullName": "David Johnson",
      "customerId": 1005,
      "userLoginid": "davidj",
      "password": "David@999",
      "emailAddress": "davidj@example.com",
      "cellPhone": "+1543987654",
      "officeLandline": "+9345678901",
      "officeAddress": "567 Birch St, Downtown",
      "department": "Sales",
      "city": "Phoenix",
      "roleId": 6,
      "sms": false,
      "mail": true,
      "userStatus": "Inactive",
      "createdBy": "admin",
      "creationDate": "2023-12-20 09:00:00",
      "roleType": "User"
    },
    {
      "userId": 6,
      "fullName": "Sophia Martinez",
      "customerId": 1006,
      "userLoginid": "sophiam",
      "password": "Sophia@321",
      "emailAddress": "sophiam@example.com",
      "cellPhone": "+1987456123",
      "officeLandline": "+9456123789",
      "officeAddress": "890 Cedar St, Suburb",
      "department": "Support",
      "city": "San Diego",
      "roleId": 7,
      "sms": true,
      "mail": false,
      "userStatus": "Active",
      "createdBy": "supervisor",
      "creationDate": "2023-11-30 11:15:00",
      "roleType": "Team Lead"
    },
    {
      "userId": 7,
      "fullName": "James Anderson",
      "customerId": 1007,
      "userLoginid": "jamesa",
      "password": "James@654",
      "emailAddress": "jamesa@example.com",
      "cellPhone": "+1765987432",
      "officeLandline": "+9564123789",
      "officeAddress": "678 Spruce St, Uptown",
      "department": "Operations",
      "city": "Dallas",
      "roleId": 8,
      "sms": true,
      "mail": true,
      "userStatus": "Active",
      "createdBy": "manager",
      "creationDate": "2023-10-10 15:30:00",
      "roleType": "Manager"
    },
    {
      "userId": 8,
      "fullName": "Olivia Roberts",
      "customerId": 1008,
      "userLoginid": "oliviar",
      "password": "Olivia@852",
      "emailAddress": "oliviar@example.com",
      "cellPhone": "+1456789023",
      "officeLandline": "+9678123456",
      "officeAddress": "234 Maple St, City Center",
      "department": "Legal",
      "city": "San Francisco",
      "roleId": 9,
      "sms": false,
      "mail": true,
      "userStatus": "Inactive",
      "createdBy": "admin",
      "creationDate": "2023-09-05 13:45:00",
      "roleType": "Legal Advisor"
    }
];

// List of US states
export const usStates = [
  'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',
  'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
  'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
  'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
  'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
  'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
  'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia',
  'Wisconsin', 'Wyoming', 'Puerto Rico',
];
