export const mockdata=
[
    
    {
      "headerName": "Charts & Analysis",
      "navbars": [
        {
          "navbarId": 6,
          "name": "Charts",
          "controllerName": "Charts",
          "actionName": "Charts",
          "area": "yes",
          "imageClass": "fa fa-bar-chart",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "1",
          "moduleName": "MDMS",
          "navbarHeaderid": 2
        },
        {
          "navbarId": 29,
          "name": "Overload",
          "controllerName": "Charts",
          "actionName": "Overload",
          "area": "21",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "MDMS",
          "navbarHeaderid": 2,
          "subItems":[ {
            "navbarId": 30,
            "name": "Underload",
            "controllerName": "Charts",
            "actionName": "Underload",
            "area": "21",
            "imageClass": "fa fa-diamond",
            "status": "TRUE",
            "parentId": 0,
            "isParent": "FALSE",
            "haschild": "0",
            "moduleName": "MDMS",
            "navbarHeaderid": 2
          },
          {
            "navbarId": 59,
            "name": "Daily Consumption",
            "controllerName": "Charts",
            "actionName": "GetDailyConsumption",
            "area": "12",
            "imageClass": "fa fa-diamond",
            "status": "FALSE",
            "parentId": 89,
            "isParent": "FALSE",
            "haschild": "0",
            "moduleName": "analogics/charts/daily-consumption",
            "navbarHeaderid": 2
          },
          {
            "navbarId": 60,
            "name": "Hourly Consumption",
            "controllerName": "Charts",
            "actionName": "GetHourlyConsumption",
            "area": "12",
            "imageClass": "fa fa-diamond",
            "status": "TRUE",
            "parentId": 89,
            "isParent": "FALSE",
            "haschild": "0",
            "moduleName": "analogics/charts/hourly-consumption",
            "navbarHeaderid": 2
          },
          {
            "navbarId": 89,
            "name": "Consumption",
            "controllerName": "Charts",
            "actionName": "Charts",
            "area": "NO",
            "imageClass": "fa fa-diamond",
            "status": "TRUE",
            "parentId": 6,
            "isParent": "TRUE",
            "haschild": "1",
            "moduleName": "MDMS",
            "navbarHeaderid": 2
          },],
        },
       
        {
          "navbarId": 90,
          "name": "Demand",
          "controllerName": "Charts",
          "actionName": "Charts",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 6,
          "isParent": "TRUE",
          "haschild": "1",
          "moduleName": "MDMS",
          "navbarHeaderid": 2
        },
        {
          "navbarId": 61,
          "name": "Daily Demand",
          "controllerName": "Charts",
          "actionName": "GetDailyDemand",
          "area": "12",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 90,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/charts/daily-demand",
          "navbarHeaderid": 2
        },
        {
          "navbarId": 93,
          "name": "Monthly Consumption",
          "controllerName": "Charts",
          "actionName": " monthlyconsumption",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 89,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/charts/montly-consumption",
          "navbarHeaderid": 2
        },
        {
          "navbarId": 7,
          "name": "Analysis",
          "controllerName": "Charts",
          "actionName": "Analysis",
          "area": "yes",
          "imageClass": "fa fa-bar-chart",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "1",
          "moduleName": "MDMS",
          "navbarHeaderid": 2
        },
        {
          "navbarId": 62,
          "name": "Hourly Demand",
          "controllerName": "Charts",
          "actionName": "GetHourlyDemand",
          "area": "12",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 90,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/charts/hourly-demand",
          "navbarHeaderid": 2
        },
        {
          "navbarId": 67,
          "name": "Potential Missing",
          "controllerName": "Analysis",
          "actionName": "Analysis",
          "area": "yes",
          "imageClass": "",
          "status": "",
          "parentId": 7,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/charts/potential-missing",
          "navbarHeaderid": 2
        },
        {
          "navbarId": 68,
          "name": "CT Reversal",
          "controllerName": "Analysis",
          "actionName": "Analysis",
          "area": "yes",
          "imageClass": "",
          "status": "",
          "parentId": 7,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/charts/ct-reversal",
          "navbarHeaderid": 2
        },
        {
          "navbarId": 69,
          "name": "Current Missing",
          "controllerName": "Analysis",
          "actionName": "Analysis",
          "area": "yes",
          "imageClass": "",
          "status": "",
          "parentId": 7,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/charts/current-missing",
          "navbarHeaderid": 2
        },
        {
          "navbarId": 70,
          "name": "CT Open",
          "controllerName": "Analysis",
          "actionName": "Analysis",
          "area": "yes",
          "imageClass": "",
          "status": "",
          "parentId": 7,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/charts/ct-open",
          "navbarHeaderid": 2
        },
        {
          "navbarId": 71,
          "name": "Current Unbalance",
          "controllerName": "Analysis",
          "actionName": "Analysis",
          "area": "yes",
          "imageClass": "",
          "status": "",
          "parentId": 7,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/charts/current-unbalance",
          "navbarHeaderid": 2
        },
        {
          "navbarId": 66,
          "name": "Event Summary",
          "controllerName": "Analysis",
          "actionName": "Analysis",
          "area": "yes",
          "imageClass": "",
          "status": "",
          "parentId": 7,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/charts/event-summary",
          "navbarHeaderid": 2
        },
        {
          "navbarId": 55,
          "name": "Meter Events",
          "controllerName": "Report",
          "actionName": "Meter Events",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 7,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/meter-events",
          "navbarHeaderid": 2
        },
        {
          "navbarId": 97,
          "name": "Tampers Restored Data",
          "controllerName": "Configuration",
          "actionName": "Tampers Restored Data",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/charts/tampersrestored-dashboard",
          "navbarHeaderid": 2
        },
        {
          "navbarId": 98,
          "name": "Tampers Not Restored Data",
          "controllerName": "Configuration",
          "actionName": "Tampers Not Restored Data",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/charts/tampers-dashboard",
          "navbarHeaderid": 2
        },
        {
          "navbarId": 100,
          "name": "Day wise Cmri Upload Details",
          "controllerName": "Configuration",
          "actionName": "Day wise Cmri Upload Details",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/charts/daywisecmri",
          "navbarHeaderid": 2
        }
      ],
      "navbarHeaderId": 2
    },
    {
      "headerName": "Configuration",
      "navbars": [
        {
          "navbarId": 82,
          "name": "Old MeterMaster Details",
          "controllerName": "Configuration",
          "actionName": "MeterMasterConfiguration",
          "area": "52",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 15,
          "isParent": "FLASE",
          "haschild": "0",
          "moduleName": "analogics/configurations/old-metermasterdetails",
          "navbarHeaderid": 5
        },
        {
          "navbarId": 31,
          "name": "Validation Failure Report",
          "controllerName": "Configuration",
          "actionName": "ValidationFailed",
          "area": "42",
          "imageClass": "fa fa-bolt",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "MDMS",
          "navbarHeaderid": 5
        },
        {
          "navbarId": 32,
          "name": "Master Data Upload",
          "controllerName": "Configuration",
          "actionName": "UploadFile",
          "area": "52",
          "imageClass": "fa fa-bolt",
          "status": "TRUE",
          "parentId": 15,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/configurations/fileupload",
          "navbarHeaderid": 5
        },
        {
          "navbarId": 14,
          "name": "User Management",
          "controllerName": "UserManagement",
          "actionName": "sos",
          "area": null,
          "imageClass": "fa fa-bolt",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/configurations/user-management",
          "navbarHeaderid": 5
        },
        {
          "navbarId": 11,
          "name": "Role Management",
          "controllerName": "Configuration",
          "actionName": "ValidationEngine",
          "area": null,
          "imageClass": "fa fa-bolt",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/configurations/role-management",
          "navbarHeaderid": 5
        },
        {
          "navbarId": 34,
          "name": "Disabled Meters",
          "controllerName": "Configuration",
          "actionName": "DisabledMeters",
          "area": "52",
          "imageClass": "fa fa-bolt",
          "status": "TRUE",
          "parentId": 15,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/configurations/disable-meters",
          "navbarHeaderid": 5
        },
        {
          "navbarId": 35,
          "name": "OldMeter/NewMeter Replace",
          "controllerName": "Configuration",
          "actionName": "MeterReplacement",
          "area": "52",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 15,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/configurations/meter-replacement",
          "navbarHeaderid": 5
        },
        {
          "navbarId": 94,
          "name": "Master Data View",
          "controllerName": "Configuration",
          "actionName": "masterdataview",
          "area": "52",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 15,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/configurations/masterdata-view",
          "navbarHeaderid": 5
        },
        {
          "navbarId": 15,
          "name": "Meter Management",
          "controllerName": "Configuration",
          "actionName": "Index",
          "area": "yes",
          "imageClass": "fa fa-bolt",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "1",
          "moduleName": "MDMS",
          "navbarHeaderid": 5
        },
        {
          "navbarId": 33,
          "name": "Master Data",
          "controllerName": "Configuration",
          "actionName": "MeterMasterConfiguration",
          "area": "52",
          "imageClass": "fa fa-bolt",
          "status": "TRUE",
          "parentId": 15,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/configurations/master-data",
          "navbarHeaderid": 5
        },
        {
          "navbarId": 65,
          "name": "Meter Map View",
          "controllerName": "Configuration",
          "actionName": "Meter Map View",
          "area": null,
          "imageClass": "fa fa-bolt",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/configurations/maps",
          "navbarHeaderid": 5
        },
        {
          "navbarId": 36,
          "name": "Inventory Data Upload",
          "controllerName": "Configuration",
          "actionName": "UploadFileInventory",
          "area": "53",
          "imageClass": "fa fa-bolt",
          "status": "TRUE",
          "parentId": 15,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/configurations/inventory-data-upload",
          "navbarHeaderid": 5
        },
        {
          "navbarId": 77,
          "name": "Group Management",
          "controllerName": "Configuration",
          "actionName": "Index",
          "area": "yes",
          "imageClass": "fa fa-bolt",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "1",
          "moduleName": "MDMS",
          "navbarHeaderid": 5
        },
        {
          "navbarId": 79,
          "name": "Listed Groups",
          "controllerName": "Configuration",
          "actionName": "Index",
          "area": null,
          "imageClass": "fa fa-bolt",
          "status": "TRUE",
          "parentId": 77,
          "isParent": "FALSE",
          "haschild": "1",
          "moduleName": "analogics/configurations/groups",
          "navbarHeaderid": 5
        },
        {
          "navbarId": 78,
          "name": "Create New Group",
          "controllerName": "Configuration",
          "actionName": "Index",
          "area": null,
          "imageClass": "fa fa-bolt",
          "status": "TRUE",
          "parentId": 77,
          "isParent": "FALSE",
          "haschild": "1",
          "moduleName": "analogics/configurations/group-management",
          "navbarHeaderid": 5
        },
        {
          "navbarId": 99,
          "name": "Cmri Upload Details",
          "controllerName": "Configuration",
          "actionName": "Cmri Upload Details",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/configurations/cmriupload-details",
          "navbarHeaderid": 5
        },
        {
          "navbarId": 101,
          "name": "Inventory Data",
          "controllerName": "Configuration",
          "actionName": "Inventory Data",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 15,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/configurations/inventory-data",
          "navbarHeaderid": 5
        }
      ],
      "navbarHeaderId": 5
    },
    {
      "headerName": "Prepaid",
      "navbars": [
        {
          "navbarId": 42,
          "name": "Tariff Configuration",
          "controllerName": "Mbc",
          "actionName": "TariffConfiguration",
          "area": "62",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 18,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/prepaid/energy-charges",
          "navbarHeaderid": 6
        },
        {
          "navbarId": 18,
          "name": "Prepaid Engine",
          "controllerName": "Prepaid",
          "actionName": "Prepaid Engine",
          "area": "yes",
          "imageClass": "fa fa-bar-chart",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "TRUE",
          "haschild": "1",
          "moduleName": "MDMS",
          "navbarHeaderid": 6
        },
        {
          "navbarId": 80,
          "name": "Prepaid Payment Topup",
          "controllerName": "Prepaid",
          "actionName": "PrepaidMeters",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 17,
          "isParent": "FLASE",
          "haschild": "0",
          "moduleName": "analogics/prepaid/prepaid-topup",
          "navbarHeaderid": 6
        },
        {
          "navbarId": 81,
          "name": "Prepaid Payment Details",
          "controllerName": "Prepaid",
          "actionName": "PrepaidMeters",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 17,
          "isParent": "FLASE",
          "haschild": "0",
          "moduleName": "analogics/prepaid/payment-details",
          "navbarHeaderid": 6
        },
        {
          "navbarId": 41,
          "name": "Meter Status",
          "controllerName": "Prepaid",
          "actionName": "PrepaidMeters",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 17,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/prepaid/prepaidmeters",
          "navbarHeaderid": 6
        },
        {
          "navbarId": 40,
          "name": "Meter Current Status",
          "controllerName": "Mbc",
          "actionName": "MeterCurrentStatus",
          "area": "61",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "MDMS",
          "navbarHeaderid": 6
        },
        {
          "navbarId": 17,
          "name": "Prepaid Reports",
          "controllerName": "Prepaid",
          "actionName": "Prepaid Reports",
          "area": "yes",
          "imageClass": "fa fa-bar-chart",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "TRUE",
          "haschild": "1",
          "moduleName": "MDMS",
          "navbarHeaderid": 6
        },
        {
          "navbarId": 38,
          "name": "Day Wise Bill Deduction",
          "controllerName": "Prepaid",
          "actionName": "DayWiseBillDeduction",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 17,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/prepaid/daywisebilldeduction",
          "navbarHeaderid": 6
        },
        {
          "navbarId": 37,
          "name": "Billing Deduction",
          "controllerName": "Prepaid",
          "actionName": "BillingDeduction",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 17,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/prepaid/billdeduction",
          "navbarHeaderid": 6
        },
        {
          "navbarId": 39,
          "name": "Ledger Report",
          "controllerName": "Prepaid",
          "actionName": "LedgerReport",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 17,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/prepaid/ledger",
          "navbarHeaderid": 6
        }
      ],
      "navbarHeaderId": 6
    },
    {
      "headerName": "Umesh",
      "navbars": [
        {
          "navbarId": 8,
          "name": "ODR Connect/Disconnect",
          "controllerName": "Report",
          "actionName": "OnDemandConfigurationConnect",
          "area": null,
          "imageClass": "fa fa-bolt",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "MDMS",
          "navbarHeaderid": 3
        },
        {
          "navbarId": 10,
          "name": "Disconnect Report",
          "controllerName": "Report",
          "actionName": "DisConnect",
          "area": null,
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/configurations/disconnect",
          "navbarHeaderid": 3
        },
        {
          "navbarId": 9,
          "name": "Connect Report",
          "controllerName": "Report",
          "actionName": "Connect",
          "area": null,
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/configurations/connect",
          "navbarHeaderid": 3
        },
        {
          "navbarId": 86,
          "name": "Meter Fota Upload",
          "controllerName": "Report",
          "actionName": "MeterFotaUpload",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FLASE",
          "haschild": "0",
          "moduleName": "analogics/requestondemand/meterfotaupload",
          "navbarHeaderid": 3
        },
        {
          "navbarId": 87,
          "name": "Modem Fota Upload",
          "controllerName": "Report",
          "actionName": "ModemFotaUpload",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FLASE",
          "haschild": "0",
          "moduleName": "analogics/requestondemand/modemfotaupload",
          "navbarHeaderid": 3
        },
        {
          "navbarId": 88,
          "name": "CFG File Upload",
          "controllerName": "Report",
          "actionName": "CFGFileUpload",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FLASE",
          "haschild": "0",
          "moduleName": "analogics/requestondemand/cfgfileupload",
          "navbarHeaderid": 3
        },
        {
          "navbarId": 91,
          "name": "Single Meter Write",
          "controllerName": "Report",
          "actionName": "singlemeterwrite",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/requestondemand/singlemeter-write",
          "navbarHeaderid": 3
        },
        {
          "navbarId": 92,
          "name": "Write Parameters",
          "controllerName": "Report",
          "actionName": "writeparameters",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/requestondemand/write-parameters",
          "navbarHeaderid": 3
        },
        {
          "navbarId": 63,
          "name": "ODR Report",
          "controllerName": "Report",
          "actionName": "ODRData",
          "area": null,
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/requestondemand/odrreport",
          "navbarHeaderid": 3
        },
        {
          "navbarId": 64,
          "name": "ODR",
          "controllerName": "Report",
          "actionName": "OnDemandConfiguration",
          "area": null,
          "imageClass": "fa fa-bolt",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/requestondemand/ondemand-configuration",
          "navbarHeaderid": 3
        }
      ],
      "navbarHeaderId": 3
    },
    {
      "headerName": "Umesg",
      "navbars": [
        {
          "navbarId": 2,
          "name": "Profile Reports",
          "controllerName": "Report",
          "actionName": "Profile Reports",
          "area": "yes",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "1",
          "moduleName": "MDMS",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 83,
          "name": "Phase Wise Communication Details",
          "controllerName": "Reports",
          "actionName": "Reports",
          "area": null,
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FLASE",
          "haschild": "0",
          "moduleName": "analogics/dashboard/dashboard-phase",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 19,
          "name": "Load Profile",
          "controllerName": "Report",
          "actionName": "CedLoadSurvey",
          "area": "12",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 2,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/load",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 20,
          "name": "Daily Profile",
          "controllerName": "Report",
          "actionName": "DailyBilling",
          "area": "12",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 2,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/daily",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 21,
          "name": "Monthly Profile",
          "controllerName": "Report",
          "actionName": "CEDMonthlyBilling",
          "area": "12",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 2,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/monthly",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 22,
          "name": "Event Profile",
          "controllerName": "Report",
          "actionName": "Events",
          "area": "12",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 2,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/event",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 24,
          "name": "Real Time Tampers",
          "controllerName": "Report",
          "actionName": "Loadprofile",
          "area": "13",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 2,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/realtime-tampers",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 85,
          "name": "Instantaneous Data",
          "controllerName": "Reports",
          "actionName": "Reports",
          "area": null,
          "imageClass": "fa fa-diamond",
          "status": "FLASE",
          "parentId": 45,
          "isParent": "FLASE",
          "haschild": "0",
          "moduleName": "analogics/reports/instant-data",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 45,
          "name": "Meter Data Reports",
          "controllerName": "Report",
          "actionName": "Meter Data Reports",
          "area": "yes",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "True",
          "haschild": "1",
          "moduleName": "MDMS",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 1,
          "name": "Data Availability Report",
          "controllerName": "Report",
          "actionName": "Summary",
          "area": null,
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/data-availability",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 4,
          "name": "Query Builder",
          "controllerName": "Report",
          "actionName": "formulaBuildernew",
          "area": null,
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/query-builder",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 5,
          "name": "Query Builder Report",
          "controllerName": "Report",
          "actionName": "QueryBuilderReport",
          "area": null,
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/query-builder-data",
          "navbarHeaderid": 1
          
        },
        {
          "navbarId": 46,
          "name": "Last Not Communicated Meters",
          "controllerName": "Report",
          "actionName": "Last Not Communicated Meters",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 45,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/non-communicated-meters",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 47,
          "name": "Block Load Profile",
          "controllerName": "Report",
          "actionName": "Block Load Profile",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 45,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/block-load-profile",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 49,
          "name": "Consumer Monthly Billing",
          "controllerName": "Report",
          "actionName": "Consumer Monthly Billing",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 45,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/consumer-monthly-billing",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 51,
          "name": "Client Billing Data",
          "controllerName": "Report",
          "actionName": "Client Billing Data",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 45,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/client-billing-data",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 53,
          "name": "Load Violation Report",
          "controllerName": "Report",
          "actionName": "Load Violation Report",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 45,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/load-violation",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 54,
          "name": "Zero Consumption Report",
          "controllerName": "Report",
          "actionName": "Zero Consumption Report",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 45,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/zero-consumption",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 56,
          "name": "IR FR",
          "controllerName": "Report",
          "actionName": "IR FR",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 45,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/ir-fr-data",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 95,
          "name": "Monthly Tod Profile",
          "controllerName": "Reports",
          "actionName": "Meter Data Reports",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 45,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/monthly-tod",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 58,
          "name": "Solar Billing",
          "controllerName": "Report",
          "actionName": "Solar Billing",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "FALSE",
          "parentId": 45,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/solar-billing",
          "navbarHeaderid": 1
        },
        {
          "navbarId": 96,
          "name": "Non Billing Interval Data",
          "controllerName": "Report",
          "actionName": "Non Billing Interval Data",
          "area": "NO",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/reports/nonbillingexport",
          "navbarHeaderid": 1
        }
      ],
      "navbarHeaderId": 1
    },
    {
      "headerName": "Umesh",
      "navbars": [],
      "navbarHeaderId": 51
    },
    {
      "headerName": "Naik",
      "navbars": [
        {
          "navbarId": 13,
          "name": "Estimation",
          "controllerName": "Configuration",
          "actionName": "Index",
          "area": "yes",
          "imageClass": "fa fa-bolt",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "MDMS",
          "navbarHeaderid": 4
        },
        {
          "navbarId": 12,
          "name": "VEE",
          "controllerName": "Configuration",
          "actionName": "Index",
          "area": "yes",
          "imageClass": "fa fa-bolt",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/vee/validation-rule",
          "navbarHeaderid": 4
        },
        {
          "navbarId": 72,
          "name": "Validation",
          "controllerName": "VEE",
          "actionName": "Validation",
          "area": "yes",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 0,
          "isParent": "FALSE",
          "haschild": "1",
          "moduleName": "MDMS",
          "navbarHeaderid": 4
        },
        {
          "navbarId": 73,
          "name": "Daily Billing Validation",
          "controllerName": "VEE",
          "actionName": "Daily Billing Validation",
          "area": "yes",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 72,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/vee/dailybilling-validation",
          "navbarHeaderid": 4
        },
        {
          "navbarId": 74,
          "name": "Monthly Billing Validation",
          "controllerName": "VEE",
          "actionName": "Monthly Billing Validation",
          "area": "yes",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 72,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/vee/monthlybilling-validation",
          "navbarHeaderid": 4
        },
        {
          "navbarId": 75,
          "name": "Load Survey Validation",
          "controllerName": "VEE",
          "actionName": "Load Survey Validation",
          "area": "yes",
          "imageClass": "fa fa-diamond",
          "status": "TRUE",
          "parentId": 72,
          "isParent": "FALSE",
          "haschild": "0",
          "moduleName": "analogics/vee/loadsurvey-validation",
          "navbarHeaderid": 4
        }
      ],
      "navbarHeaderId": 4
    }
  ]